
import { Inter } from "next/font/google";
import Sidebar from "./components/sidebar/Sidebar";
import Footer from "@/components/footer/Footer";
import Header from "./components/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MedicalEncounterLayout({ children }) {
  return (
    <html lang="en">
      <body className="light">
        <Header />
        <div className="absolute w-3/12 left-0 overflow-y-auto h-[100vh]">
          {/* <Sidebar /> */}
        </div>
        <div
          style={{
            backgroundColor: "var(--body)",
          }}
          className="absolute w-full right-0"
        >
          {children}
        </div>
      </body>
    </html>
  );
}
