import Header from "@/components/ui/header/header";
import { Inter } from "next/font/google";
import SimpleHeader from "./components/header/simple-header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="light">
        <SimpleHeader />
        <div
          style={{
            backgroundColor: "var(--body)",
          }}
          className="flex items-center justify-center overflow-y-auto"
        >
          {children}
        </div>
      </body>
    </html>
  );
}
